server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    
  profiles:
    # 外置jdbc和log配置文件
    active: jdbc,log,redis,mail
  thymeleaf: 
      cache: false
  resources:
    static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
mybatis:
  type-aliases-package: slowcity.com.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

 

 